### ISSUE TITLE
panic when cache directory is cleaned

### ISSUE THREAD

**Issue by Azero-NG** [tupton/alfred-chrome-history#27]
```text
[11:22:22.216] Google Chrome History[Script Filter] Queuing argument 'ar'
[11:22:22.245] Google Chrome History[Script Filter] Script with argv '(null)' finished
[11:22:22.247] ERROR: Google Chrome History[Script Filter] Code 1: Traceback (most recent call last):
  File "chrome.py", line 137, in <module>
    db = history_db(profile, favicons=favicons)
  File "chrome.py", line 87, in history_db
    history = copy_db(HISTORY_DB, profile)
  File "chrome.py", line 74, in copy_db
    cache = os.path.join(alfred.work(True), name)
  File "/Users/xxxxxxxxxxxxxxxxxx/alfred/preferences/Alfred.alfredpreferences/workflows/user.workflow.C918F46E-3F2A-46AE-994F-3E9CA9F7A8FE/alfred.py", line 80, in work
    return _create(path)
  File "/Users/xxxxxxxxxxxxxxxxxx/alfred/preferences/Alfred.alfredpreferences/workflows/user.workflow.C918F46E-3F2A-46AE-994F-3E9CA9F7A8FE/alfred.py", line 93, in _create
    os.mkdir(path)
OSError: [Errno 2] No such file or directory: '/Users/xxxxx/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.thomasupton.chrome-history'
```

**Comment by Azero-NG** [comment]
sorry, it's alfred's fault
